FROM golang:alpine

WORKDIR /api

COPY go.mod go.sum ./

RUN go mod download

COPY ./inventory_srv ./inventory_srv

WORKDIR /api/inventory_srv
COPY ./inventory_srv/config-debug.yaml ./inventory_srv/
COPY ./inventory_srv/config-pro.yaml ./inventory_srv/

# 构建项目
RUN go build -o inventory_srv .

# 执行构建的二进制文件
CMD ["./inventory_srv"]
