FROM golang:alpine

WORKDIR /api

COPY go.mod go.sum ./

RUN go mod download

COPY ./user-web ./user-web

WORKDIR /api/user-web
COPY ./user-web/config-debug.yaml ./user-web/
COPY ./user-web/config-pro.yaml ./user-web/

# 构建项目
RUN go build -o user_web .

# 执行构建的二进制文件
CMD ["./user_web"]
